export enum ChatWidgetMessageType {
  AGENT_MESSAGE = 'CHAT_WIDGET_AGENT_MESSAGE',
  SEND_MESSAGE = 'CHAT_WIDGET_SEND_MESSAGE',
  NAVIGATE_URL = 'CHAT_WIDGET_NAVIGATE_URL',
  RESTORE_CONVERSATION = 'CHAT_WIDGET_RESTORE_CONVERSATION',
  CONVERSATION_RESTORED = 'CHAT_WIDGET_CONVERSATION_RESTORED',
  REQUEST_CONVERSATION_ID = 'CHAT_WIDGET_REQUEST_CONVERSATION_ID',
  CONVERSATION_ID_RESPONSE = 'CHAT_WIDGET_CONVERSATION_ID_RESPONSE',
}

export enum PusherEventType {
  AGENT_MESSAGE = 'agent.message',
}